compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN:-}"

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.8.0.cjs
